- hosts: ec2
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache (apache2)
      apt:
        name: apache2
        state: present

    - name: Create a custom HTML page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Welcome</title>
            <style>
              body {
                background-color: Green;
                color: white;
                font-size: 24px;
                text-align: center;
                padding-top: 20%;
              }
            </style>
          </head>
          <body>
            Hello from Mohanad!
          </body>
          </html>

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: true
